#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.1'

services:
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: pms
      MYSQL_USER: student
      MYSQL_PASSWORD: secret
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:z
  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
      PMA_USER: student 
      PMA_PASSWORD: secret 
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 8192
    restart: always
    ports:
      - 8080:80
